### PR TITLE
fix: prevent text edge labels from overflowing narrow compound subgraph columns

### LINKED ISSUE #223: Text edge labels overflow narrow compound subgraph column widths
## Description

In text output, long edge labels can overflow the width of a narrow compound subgraph column, bleeding into adjacent columns. This is most visible with concurrent regions where each region gets a fraction of the total width, but applies to any narrow compound subgraph.

## Reproduction

```mermaid
stateDiagram-v2
    state Active {
        [*] --> ScrollLockOff
        ScrollLockOff --> ScrollLockOn : EvScrollLockPressed
        ScrollLockOn --> ScrollLockOff : EvScrollLockPressed
        --
        [*] --> CapsLockOff
        CapsLockOff --> CapsLockOn : EvCapsLockPressed
        CapsLockOn --> CapsLockOff : EvCapsLockPressed
    }
```

The label "EvScrollLockPressed" is wider than its region column, so it bleeds across the region divider into the adjacent region's space.

## Expected behavior

Labels should either be truncated/wrapped to fit within the column, or the column width should be expanded to accommodate the longest label.

## Context

The text grid allocates column widths based on node sizes during grid derivation. Edge label widths are not factored into the minimum column width calculation. This becomes visible with concurrent regions (narrow columns) but is a general text grid constraint issue.

### PR DESCRIPTION
**Pull request by kevinswiber**
## Summary

- Adds grid layout expansion (Phase K.5) to widen narrow subgraph columns when internal edge labels are wider than the available space — concurrent regions are processed left-to-right, shifting subsequent siblings
- Adds renderer-side label clamping to the tightest containing subgraph bounds, preventing overflow when the renderer places labels to one side of the edge segment
- Regenerates affected text snapshots (concurrent_three, subgraph_direction_nested_both/mixed)

## Test plan

- [x] All 2409 tests pass (`just check`)
- [x] `EvScrollLockPressed` label stays within its concurrent region column
- [x] Long labels in nested subgraphs with direction overrides render correctly
- [x] No regressions in flowchart or state diagram snapshots

Closes #223

### CODE REVIEW

File: src/graph/grid/derive/subgraph_bounds.rs [hunk 1]
```diff
@@ -871,3 +871,163 @@ pub(super) fn ensure_subgraph_contains_members(
...
+
+            // Apply cumulative shift from previous region expansions.
+            if cumulative_shift > 0 {
+                if let Some(rb) = subgraph_bounds.get_mut(region_id) {
+                    rb.x += cumulative_shift;
+                }
+                for member_id in &region_members {
+                    shift_node_x(member_id, cumulative_shift, node_bounds, draw_positions);
+                    shifted_nodes.insert(member_id.clone());
+                    if let Some(child_sb) = subgraph_bounds.get_mut(member_id) {
```
Comment (kevinswiber) [inline src/graph/grid/derive/subgraph_bounds.rs]: When `member_id` is a child subgraph, this shifts only that subgraph border and leaves all of its descendant node bounds/draw positions behind. I can reproduce it with a concurrent state where region 1 has a long label and region 2 contains `state Inner { I1 --> I2 }`: the widened first region pushes region 2 right, but `Inner` moves away from `I1`/`I2`. This needs to move compound members recursively, not just adjust the child `SubgraphBounds.x`.
